### ISSUE TITLE
Call signature - missing return type

### ISSUE THREAD

**Issue by danielpeintner** [duxiaofeng-github/typescript-json-schema-faker#1]
Hi,

I was using typescript-json-schema-faker and I get the following error.

`node_modules/typescript-json-schema-faker/index.d.ts(88,3): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.`

The issue seems to be in

```
interface TypescriptJsonSchemaFakerStatic {
  (schema: JsonSchema, refs?: any);
}
```

**Comment by duxiaofeng-github** [comment]
ok, let me look into it, maybe i should add some test case.

**Comment by duxiaofeng-github** [comment]
ok, i rewrited it by typescript and generate definition by typescript it self. have a try.

**Comment by duxiaofeng-github** [comment]
i also add some unit test written by typescript, it built successful and all test case are passed by now.
